/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SharingInformation } from "./SharingInformation";
import { SharingInformationCountArgs } from "./SharingInformationCountArgs";
import { SharingInformationFindManyArgs } from "./SharingInformationFindManyArgs";
import { SharingInformationFindUniqueArgs } from "./SharingInformationFindUniqueArgs";
import { DeleteSharingInformationArgs } from "./DeleteSharingInformationArgs";
import { SharingInformationService } from "../sharingInformation.service";
@graphql.Resolver(() => SharingInformation)
export class SharingInformationResolverBase {
  constructor(protected readonly service: SharingInformationService) {}

  async _sharingInformationsMeta(
    @graphql.Args() args: SharingInformationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SharingInformation])
  async sharingInformations(
    @graphql.Args() args: SharingInformationFindManyArgs
  ): Promise<SharingInformation[]> {
    return this.service.sharingInformations(args);
  }

  @graphql.Query(() => SharingInformation, { nullable: true })
  async sharingInformation(
    @graphql.Args() args: SharingInformationFindUniqueArgs
  ): Promise<SharingInformation | null> {
    const result = await this.service.sharingInformation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SharingInformation)
  async deleteSharingInformation(
    @graphql.Args() args: DeleteSharingInformationArgs
  ): Promise<SharingInformation | null> {
    try {
      return await this.service.deleteSharingInformation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
